# Site settings
title: 신나는연구소
email: comchangs+excitinglab@gmail.com
description: 신나는연구소 - 신나는 일을 하며 삽시다!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "excitinglab.com" # the base hostname & protocol for your site

# User setting
owner: 신나는연구소
email: comchangs+excitinglab@gmail.com
facebook_username: excitinglab
twitter_username:
github_username: excitinglab
address:
  - line:
  - line:
  # Feel free to add more lines here
telephone:
copyright: 신나는연구소

# API settings
google_api_key:

# Build settings
markdown: kramdown
